# Generated by Django 3.2.9 on 2022-09-09 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(8)])),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('fileID', models.IntegerField(blank=True, null=True, unique=True)),
                ('price', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(10000000)])),
                ('submit_Date', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False)),
                ('done_Date', models.DateTimeField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('a', 'active'), ('v', 'verified'), ('p', 'pending'), ('r', 'refused'), ('c', 'cancelled'), ('d', 'done')], default='a', max_length=1)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('p', 'Project'), ('r', 'Request'), ('b', 'Bug')], default='b', max_length=1)),
                ('title', models.CharField(max_length=40)),
                ('details', models.TextField(blank=True, null=True)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('b', 'Ban'), ('w', 'Warning'), ('f', 'False'), ('p', 'Pending'), ('s', 'Solved'), ('i', 'Ignored')], default='p', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReqProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('has_seen', models.BooleanField(default=False)),
                ('applied', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
